In [ ]:
import numpy as np
import pandas as pd

# NumPy Array

In [ ]:
lista = [1, 2 , 3, 4, 5, 6, 7, 8, 9]
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
arr = np.array(lista)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
matriz = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
matriz = np.array(matriz)
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Indexing

In [ ]:
arr[0]

1

In [ ]:
arr[0] + arr[5]

7

In [ ]:
matriz[0]

array([1, 2, 3])

In [ ]:
matriz[0, 2]

3

## Slicing

In [ ]:
arr[1:6]

array([2, 3, 4, 5, 6])

In [ ]:
arr[:6]

array([1, 2, 3, 4, 5, 6])

In [ ]:
arr[::3]

array([1, 4, 7])

In [ ]:
matriz[1:]

array([[4, 5, 6],
       [7, 8, 9]])

In [ ]:
matriz[1:, 0:2]

array([[4, 5],
       [7, 8]])

# Tipos de datos

In [ ]:
arr = np.array([1, 2, 3, 4])
arr.dtype

dtype('int64')

In [ ]:
arr = np.array([1, 2, 3, 4], dtype = 'float64')
arr.dtype

dtype('float64')

In [ ]:
arr

array([1., 2., 3., 4.])

In [ ]:
arr = np.array([1, 2, 3, 4])
arr = arr.astype(np.float64)
arr

array([1., 2., 3., 4.])

In [ ]:
arr = np.array([0, 1, 2, 3, 4])
arr = arr.astype(np.bool_)
arr

array([False,  True,  True,  True,  True])

In [ ]:
arr = np.array([0, 1, 2, 3, 4])
arr = arr.astype(np.string_)
arr

array([b'0', b'1', b'2', b'3', b'4'], dtype='|S21')

In [ ]:
arr = np.array(['0', '1', '2', '3', '4'])
arr = arr.astype(np.int8)
arr

array([0, 1, 2, 3, 4], dtype=int8)

# Dimensiones

In [ ]:
scalar = np.array(42)
print(scalar)
scalar.ndim

42


0

In [ ]:
vector = np.array([1, 2, 3])
print(vector)
vector.ndim

[1 2 3]


1

In [ ]:
matriz = np.array([[1, 2, 3], [4, 5, 6]])
print(matriz)
matriz.ndim

[[1 2 3]
 [4 5 6]]


2

In [ ]:
tensor = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]],[[13, 13, 15], [16, 17, 18], [19, 20, 21], [22, 23, 24]]])
print(tensor)
tensor.ndim

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]

 [[13 13 15]
  [16 17 18]
  [19 20 21]
  [22 23 24]]]


3

## Agregar o eliminar dimensiones

In [ ]:
vector = np.array([1, 2, 3], ndmin = 10)
print(vector)
vector.ndim

[[[[[[[[[[1 2 3]]]]]]]]]]


10

In [ ]:
expand = np.expand_dims(np.array([1, 2, 3]), axis = 0)
print(expand)
expand.ndim

[[1 2 3]]


2

In [ ]:
print(vector, vector.ndim)
vector_2 = np.squeeze(vector)
print(vector_2, vector_2.ndim)

[[[[[[[[[[1 2 3]]]]]]]]]] 10
[1 2 3] 1


# Crear Arrays

In [ ]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
np.zeros(3)

array([0., 0., 0.])

In [ ]:
np.zeros((10,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.ones(3)

array([1., 1., 1.])

In [ ]:
np.linspace(0, 10 , 10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [ ]:
# Matriz diagonal
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
np.random.rand()

0.7684662812382598

In [ ]:
np.random.rand(4)

array([0.71391726, 0.78448866, 0.06194453, 0.899199  ])

In [ ]:
np.random.rand(4,4)

array([[0.11333497, 0.29887844, 0.26840151, 0.34791811],
       [0.5221507 , 0.81421262, 0.02728703, 0.76143043],
       [0.37375363, 0.63270092, 0.46507592, 0.63513825],
       [0.75192577, 0.34652811, 0.36776666, 0.65893972]])

In [ ]:
np.random.randint(1,15, (3,3))

array([[ 9, 10, 13],
       [ 1, 13,  5],
       [ 6, 12,  1]])

# Shape y Reshape

## Shape

In [ ]:
arr = np.random.randint(1,10,(3,2))
arr.shape

(3, 2)

In [ ]:
arr

array([[2, 7],
       [5, 8],
       [6, 1]])

## Reshape

In [ ]:
arr.reshape(1,6)

array([[2, 7, 5, 8, 6, 1]])

In [ ]:
arr.reshape(2,3)

array([[2, 7, 5],
       [8, 6, 1]])

In [ ]:
np.reshape(arr,(1,6))

array([[2, 7, 5, 8, 6, 1]])

In [ ]:
np.reshape(arr,(2,3), 'C')

array([[2, 7, 5],
       [8, 6, 1]])

In [ ]:
np.reshape(arr,(2,3), 'F')

array([[2, 6, 8],
       [5, 7, 1]])

In [ ]:
np.reshape(arr,(2,3), 'A')

array([[2, 7, 5],
       [8, 6, 1]])

# Funciones principales de NumPy

In [ ]:
arr = np.random.randint(1, 20, 10)
arr

array([ 7, 13, 16,  1, 10, 15,  5, 11, 12,  8])

In [ ]:
matriz = arr.reshape(2,5)
matriz

array([[ 7, 13, 16,  1, 10],
       [15,  5, 11, 12,  8]])

In [ ]:
arr.max()

16

In [ ]:
matriz.max()

16

In [ ]:
arr.argmax()

2

In [ ]:
matriz.argmax(0)

array([1, 0, 0, 1, 0])

In [ ]:
arr.min()

1

In [ ]:
arr.argmin()

3

In [ ]:
matriz.min(0)

array([ 7,  5, 11,  1,  8])

In [ ]:
matriz.argmin(1)

array([3, 1])

In [ ]:
arr.ptp()

15

In [ ]:
matriz.ptp(0)

array([ 8,  8,  5, 11,  2])

## Análisis estadístico

In [ ]:
arr.sort()
arr

array([ 1,  5,  7,  8, 10, 11, 12, 13, 15, 16])

In [ ]:
np.percentile(arr, 50)

10.5

In [ ]:
np.median(arr)

10.5

In [ ]:
np.std(arr)

4.4

In [ ]:
np.var(arr)

19.36

In [ ]:
np.mean(arr)

9.8

In [ ]:
np.median(matriz, 1)

array([ 7., 13.])

## Concatenación

In [ ]:
a = np.array([[1,2], [3,4]])
b = np.array([5, 6])

In [ ]:
b = np.expand_dims(b, axis = 0)
np.concatenate((a,b), axis = 0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
# Transpuesta
b.T

array([[5],
       [6]])

In [ ]:
np.concatenate((a,b.T), axis = 1)

array([[1, 2, 5],
       [3, 4, 6]])

# Copy

.copy() nos permite copiar un array de NumPy en otra variable de tal forma que al modificar el nuevo array los cambios no se vean reflejados en array original.

In [ ]:
arr = np.arange(0, 11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
trozo_de_arr = arr[0:6]
trozo_de_arr[:] = 0
trozo_de_arr

array([0, 0, 0, 0, 0, 0])

In [ ]:
arr

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

In [ ]:
arr_copy = arr.copy()
arr_copy[:] = 100
arr_copy, arr

(array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100]),
 array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10]))

# Condiciones

In [ ]:
arr = np.linspace(1,10,10, dtype = 'int8')
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int8)

In [ ]:
indices_cond = arr > 5
indices_cond

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [ ]:
arr[indices_cond]

array([ 6,  7,  8,  9, 10], dtype=int8)

In [ ]:
arr[(arr > 5) & (arr < 9)]

array([6, 7, 8], dtype=int8)

In [ ]:
arr[arr > 5] = 99
arr

array([ 1,  2,  3,  4,  5, 99, 99, 99, 99, 99], dtype=int8)

# Operaciones

In [ ]:
lista = [1,2]
lista

[1, 2]

In [ ]:
lista * 2

[1, 2, 1, 2]

In [ ]:
arr = np.arange(0,10)
arr2 = arr.copy()
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
arr + 2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
arr**2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [ ]:
arr + arr2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
matriz = arr.reshape(2,5)
matriz2 = matriz.copy()
matriz

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
np.matmul(matriz, matriz2.T)

array([[ 30,  80],
       [ 80, 255]])

In [ ]:
matriz @ matriz2.T

array([[ 30,  80],
       [ 80, 255]])